application:
    redissonConfig:
        singleServerConfig:
            address: "redis://10.0.25.28:6379"
        threads: 0
        nettyThreads: 0
        codec: org.redisson.codec.JsonJacksonCodec
        transportMode: "NIO"